package com.cobolconverter.demo;

import java.math.BigDecimal;

public class RPVI8001 {
	
	public String VZPP_FILE_SOURCE;
	public String VZPP_BILLING_SYSTEM;
	public String VZPP_LEGAL_TYPE;
	public String VZPP_LEGAL_ENTITY_DESC;
	public Integer VZPP_DATE_RECEIVED;          
	public Integer VZPP_TIME_RECEIVED;          
	public Integer VZPP_DATE_SENT;    
	public Integer VZPP_TIME_SENT;    
	public BigDecimal VZPP_PAYMENT_AMOUNT;
	public Integer VZPP_PAYMENT_ITEMS; 
	public BigDecimal VZPP_RETURN_AMOUNT; 
	public Integer VZPP_RETURN_ITEMS;  
	public Short VZPP_PAYMENT_AMOUNT_UI;
	public Short VZPP_PAYMENT_ITEMS_UI; 
	public Short VZPP_RETURN_AMOUNT_UI; 
	public Short VZPP_RETURN_ITEMS_UI; 
	public Short VZPP_BATCH_NO;      
	public Short VZPP_FILLER1;
	public String getVZPP_BILLING_SYSTEM() {
		return VZPP_BILLING_SYSTEM;
	}
	public void setVZPP_BILLING_SYSTEM(String vZPP_BILLING_SYSTEM) {
		VZPP_BILLING_SYSTEM = vZPP_BILLING_SYSTEM;
	}
	public String getVZPP_LEGAL_TYPE() {
		return VZPP_LEGAL_TYPE;
	}
	public void setVZPP_LEGAL_TYPE(String vZPP_LEGAL_TYPE) {
		VZPP_LEGAL_TYPE = vZPP_LEGAL_TYPE;
	}
	public String getVZPP_LEGAL_ENTITY_DESC() {
		return VZPP_LEGAL_ENTITY_DESC;
	}
	public void setVZPP_LEGAL_ENTITY_DESC(String vZPP_LEGAL_ENTITY_DESC) {
		VZPP_LEGAL_ENTITY_DESC = vZPP_LEGAL_ENTITY_DESC;
	}
	public Integer getVZPP_DATE_RECEIVED() {
		return VZPP_DATE_RECEIVED;
	}
	public void setVZPP_DATE_RECEIVED(Integer vZPP_DATE_RECEIVED) {
		VZPP_DATE_RECEIVED = vZPP_DATE_RECEIVED;
	}
	public Integer getVZPP_TIME_RECEIVED() {
		return VZPP_TIME_RECEIVED;
	}
	public void setVZPP_TIME_RECEIVED(Integer vZPP_TIME_RECEIVED) {
		VZPP_TIME_RECEIVED = vZPP_TIME_RECEIVED;
	}
	public Integer getVZPP_DATE_SENT() {
		return VZPP_DATE_SENT;
	}
	public void setVZPP_DATE_SENT(Integer vZPP_DATE_SENT) {
		VZPP_DATE_SENT = vZPP_DATE_SENT;
	}
	public Integer getVZPP_TIME_SENT() {
		return VZPP_TIME_SENT;
	}
	public void setVZPP_TIME_SENT(Integer vZPP_TIME_SENT) {
		VZPP_TIME_SENT = vZPP_TIME_SENT;
	}
	public BigDecimal getVZPP_PAYMENT_AMOUNT() {
		return VZPP_PAYMENT_AMOUNT;
	}
	public void setVZPP_PAYMENT_AMOUNT(BigDecimal vZPP_PAYMENT_AMOUNT) {
		VZPP_PAYMENT_AMOUNT = vZPP_PAYMENT_AMOUNT;
	}
	public Integer getVZPP_PAYMENT_ITEMS() {
		return VZPP_PAYMENT_ITEMS;
	}
	public void setVZPP_PAYMENT_ITEMS(Integer vZPP_PAYMENT_ITEMS) {
		VZPP_PAYMENT_ITEMS = vZPP_PAYMENT_ITEMS;
	}
	public BigDecimal getVZPP_RETURN_AMOUNT() {
		return VZPP_RETURN_AMOUNT;
	}
	public void setVZPP_RETURN_AMOUNT(BigDecimal vZPP_RETURN_AMOUNT) {
		VZPP_RETURN_AMOUNT = vZPP_RETURN_AMOUNT;
	}
	public Integer getVZPP_RETURN_ITEMS() {
		return VZPP_RETURN_ITEMS;
	}
	public void setVZPP_RETURN_ITEMS(Integer vZPP_RETURN_ITEMS) {
		VZPP_RETURN_ITEMS = vZPP_RETURN_ITEMS;
	}
	public Short getVZPP_PAYMENT_AMOUNT_UI() {
		return VZPP_PAYMENT_AMOUNT_UI;
	}
	public void setVZPP_PAYMENT_AMOUNT_UI(Short vZPP_PAYMENT_AMOUNT_UI) {
		VZPP_PAYMENT_AMOUNT_UI = vZPP_PAYMENT_AMOUNT_UI;
	}
	public Short getVZPP_PAYMENT_ITEMS_UI() {
		return VZPP_PAYMENT_ITEMS_UI;
	}
	public void setVZPP_PAYMENT_ITEMS_UI(Short vZPP_PAYMENT_ITEMS_UI) {
		VZPP_PAYMENT_ITEMS_UI = vZPP_PAYMENT_ITEMS_UI;
	}
	public Short getVZPP_RETURN_AMOUNT_UI() {
		return VZPP_RETURN_AMOUNT_UI;
	}
	public void setVZPP_RETURN_AMOUNT_UI(Short vZPP_RETURN_AMOUNT_UI) {
		VZPP_RETURN_AMOUNT_UI = vZPP_RETURN_AMOUNT_UI;
	}
	public Short getVZPP_RETURN_ITEMS_UI() {
		return VZPP_RETURN_ITEMS_UI;
	}
	public void setVZPP_RETURN_ITEMS_UI(Short vZPP_RETURN_ITEMS_UI) {
		VZPP_RETURN_ITEMS_UI = vZPP_RETURN_ITEMS_UI;
	}
	public Short getVZPP_BATCH_NO() {
		return VZPP_BATCH_NO;
	}
	public void setVZPP_BATCH_NO(Short vZPP_BATCH_NO) {
		VZPP_BATCH_NO = vZPP_BATCH_NO;
	}
	public Short getVZPP_FILLER1() {
		return VZPP_FILLER1;
	}
	public void setVZPP_FILLER1(Short vZPP_FILLER1) {
		VZPP_FILLER1 = vZPP_FILLER1;
	}
	@Override
	public String toString() {
		return "RPVI8001 [VZPP_BILLING_SYSTEM=" + VZPP_BILLING_SYSTEM + ", VZPP_LEGAL_TYPE=" + VZPP_LEGAL_TYPE
				+ ", VZPP_LEGAL_ENTITY_DESC=" + VZPP_LEGAL_ENTITY_DESC + ", VZPP_DATE_RECEIVED=" + VZPP_DATE_RECEIVED
				+ ", VZPP_TIME_RECEIVED=" + VZPP_TIME_RECEIVED + ", VZPP_DATE_SENT=" + VZPP_DATE_SENT
				+ ", VZPP_TIME_SENT=" + VZPP_TIME_SENT + ", VZPP_PAYMENT_AMOUNT=" + VZPP_PAYMENT_AMOUNT
				+ ", VZPP_PAYMENT_ITEMS=" + VZPP_PAYMENT_ITEMS + ", VZPP_RETURN_AMOUNT=" + VZPP_RETURN_AMOUNT
				+ ", VZPP_RETURN_ITEMS=" + VZPP_RETURN_ITEMS + ", VZPP_PAYMENT_AMOUNT_UI=" + VZPP_PAYMENT_AMOUNT_UI
				+ ", VZPP_PAYMENT_ITEMS_UI=" + VZPP_PAYMENT_ITEMS_UI + ", VZPP_RETURN_AMOUNT_UI="
				+ VZPP_RETURN_AMOUNT_UI + ", VZPP_RETURN_ITEMS_UI=" + VZPP_RETURN_ITEMS_UI + ", VZPP_BATCH_NO="
				+ VZPP_BATCH_NO + ", VZPP_FILLER1=" + VZPP_FILLER1 + "]";
	}  

}
